on: [push]

jobs:
  first_test:
    runs-on: ubuntu-latest
    name: A job to test the action!
    steps:
      - name: Enable the awesome action!
        id: enable_action
        uses: istherepie/actions-containerspace@master

      - name: Check working directory
        run: pwd

      - name: List root fs
        run: ls -ltr /
