on: [push]

jobs:
  first_test:
    runs-on: ubuntu-latest
    name: A job to test the action!
    steps:
      - name: Enable the awesome action!
        id: enable_action
        uses: istherepie/actions-containerspace@master

      - name: Check working directory
        run: pwd

      - name: List github home directory
        run: ls -ltr /home/runner/work/_temp/_github_home
      
      - name: Echo readme
        run: cat README.md


