on: [push]

jobs:
  first_test:
    name: A job to test the action!
    environment: testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable the awesome action!
        id: enable_action
        uses: istherepie/actions-containerspace@master

      - name: Check working directory
        run: pwd
      
      - name: Echo readme
        run: cat README.md
      
      - name: Run MOTD script
        run: sh scripts/hello.sh
